name: This is new web_page
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  new_build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install nginx
        run: apt-get update -y && apt-get install nginx -y
      - name: Copy index.html
        run: cp index.html /var/www/index.html
  
