name: This is new web_page
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  new_build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v1
      - name: Pyhton run
        run: python3 git.py

  
